In [41]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt("../data/train_xor.txt", unpack=True)
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_uniform([2, 5], -1.0, 1.0))
#w1 = tf.get_variable("W", shape=[784, 256], initializer=tf.contrib.layers.xavier_initializer())
w2 = tf.Variable(tf.random_uniform([5, 10], -1.0, 1.0))
w3 = tf.Variable(tf.random_uniform([10, 10], -1.0, 1.0), name='weight3')
w4 = tf.Variable(tf.random_uniform([10, 10], -1.0, 1.0), name='weight4')
w5 = tf.Variable(tf.random_uniform([10, 10], -1.0, 1.0), name='weight5')
w6 = tf.Variable(tf.random_uniform([10, 10], -1.0, 1.0), name='weight6')
w7 = tf.Variable(tf.random_uniform([10, 10], -1.0, 1.0), name='weight7')
w8 = tf.Variable(tf.random_uniform([10, 1], -1.0, 1.0), name='weight8')

b1 = tf.Variable(tf.zeros([5]), name="Bias1")
b3 = tf.Variable(tf.zeros([10]), name="Bias3")
b2 = tf.Variable(tf.zeros([10]), name="Bias2")
b4 = tf.Variable(tf.zeros([10]), name="Bias4")
b5 = tf.Variable(tf.zeros([10]), name="Bias5")
b6 = tf.Variable(tf.zeros([10]), name="Bias6")
b7 = tf.Variable(tf.zeros([10]), name="Bias7")
b8 = tf.Variable(tf.zeros([1]), name="Bias8")


#L2 = tf.nn.relu(tf.matmul(X, W1) + b1)
#L2 = tf.nn.relu(tf.matmul(X,w1)+b1)
# dropdout 
dropout_rate = tf.placeholder("float")
_L2 = tf.nn.relu(tf.matmul(X,w1)+b1)
L2 = tf.nn.dropout(_L2, dropout_rate)

L3 = tf.nn.relu(tf.matmul(L2,w2)+b2)
L4 = tf.nn.relu(tf.matmul(L3,w3)+b3)
L5 = tf.nn.relu(tf.matmul(L4,w4)+b4)
L6 = tf.nn.relu(tf.matmul(L5,w5)+b5)
L7 = tf.nn.relu(tf.matmul(L6,w6)+b6)
L8 = tf.nn.relu(tf.matmul(L7,w7)+b7)

hypothesis = tf.sigmoid(tf.matmul(L8, w8) + b8)

cost = -tf.reduce_mean((Y*tf.log(hypothesis)) + ((1-Y)*tf.log(1.-hypothesis)))

a = tf.Variable(0.1)
opt = tf.train.GradientDescentOptimizer(a)
train = opt.minimize(cost)

init = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init)

    for step in range(1000):
        dropout_val = 0.7
        sess.run(train, feed_dict={X: x_data, Y: y_data, dropout_rate :dropout_val})
        if step % 200 == 0:
            print ("Step :", step)
            print ("Cost :", sess.run(cost, feed_dict={X: x_data, Y: y_data, dropout_rate : dropout_val}))
            print ("W1 :", sess.run(w1))
            print ("W2 :", sess.run(w2))
    
    co_predict = tf.equal(tf.floor(hypothesis + 0.5), Y)
    
    dropout_val_verify = 1.0
    acc = tf.reduce_mean(tf.cast(co_predict, "float"))
    print(sess.run([hypothesis, tf.floor(hypothesis + 0.5), co_predict, acc], feed_dict={X: x_data, Y: y_data, dropout_rate : dropout_val_verify}))
    print("Acc:", acc.eval({X:x_data, Y: y_data, dropout_rate : dropout_val_verify}))

Step : 0
Cost : 0.658144
W1 : [[ 0.96522534  0.10295771 -0.10062432  0.78384823 -0.32085276]
 [ 0.62992579 -0.09051564  0.05933046 -0.09388682 -0.70116353]]
W2 : [[ 0.87189889  0.20937496  0.07599401  0.18106566  0.21491003  0.86127448
  -0.62336707 -0.21130276 -0.71692729 -0.16511677]
 [ 0.70406777  0.00669788 -0.46864796 -0.93554133 -0.73349059 -0.70591325
   0.85372448  0.57255125  0.94604039  0.71113825]
 [-0.52682352 -0.36710453 -0.1129024  -0.92550516 -0.88367963 -0.80818057
  -0.80595541 -0.53244805  0.02429438  0.02639914]
 [ 0.24585502  0.14919333 -0.94863248  0.78582406  0.42657936 -0.2105207
  -0.03956294 -0.97087002  0.66540313  0.2570639 ]
 [ 0.88795996 -0.93783927  0.40554643 -0.4731338  -0.46408963  0.63510323
   0.35728145  0.70094466 -0.84446383 -0.18268824]]
Step : 200
Cost : 0.235595
W1 : [[  9.64420021e-01   5.32326922e-02  -1.00624323e-01   7.03851342e-01
   -3.20852757e-01]
 [  9.26180720e-01  -9.05156434e-02   7.14406371e-04  -6.38494790e-01
   -7.01163530e-01]]


In [12]:
import numpy as np
import tensorflow as tf

xy = np.loadtxt('../data/train_xor.txt', unpack=True)

# Need to change data structure. THESE LINES ARE DIFFERNT FROM Video BUT IT MAKES THIS CODE WORKS!
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2,2], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [2,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis = tf.sigmoid( tf.matmul(L2,W2) + b2)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )

0 0.710155 [[ 0.93656242  0.58791101]
 [-0.90597105 -0.79407078]] [[ 0.87197995]
 [-0.16757829]]
1000 0.672772 [[ 1.12575221  0.79828292]
 [-1.63173401 -0.7825554 ]] [[ 1.2305758 ]
 [-0.53120208]]
2000 0.458045 [[ 3.01096201  2.0982182 ]
 [-3.39414954 -1.84060967]] [[ 3.44079399]
 [-2.16215777]]
3000 0.139035 [[ 4.50007963  4.12558985]
 [-4.72703362 -3.85067058]] [[ 5.9372201 ]
 [-5.13256454]]
4000 0.0647232 [[ 5.09700012  4.94563484]
 [-5.2955637  -4.674438  ]] [[ 7.30792809]
 [-6.66909504]]
5000 0.0404848 [[ 5.41942787  5.37020969]
 [-5.61359501 -5.10132265]] [[ 8.15488434]
 [-7.57173586]]
6000 0.0290807 [[ 5.63263321  5.64404774]
 [-5.8271265  -5.37665606]] [[ 8.7570076 ]
 [-8.19939041]]
7000 0.0225633 [[ 5.78945541  5.84220695]
 [-5.98545742 -5.57584381]] [[ 9.22152042]
 [-8.67795753]]
8000 0.0183782 [[ 5.91242552  5.99577427]
 [-6.11020517 -5.73014736]] [[ 9.59868813]
 [-9.06379604]]
[array([[ 0.01783025],
       [ 0.9759379 ],
       [ 0.98407966],
       [ 0.01500318]], dtype=fl

In [16]:
!python3 NN.py

[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]
[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]]
0 0.692894 [[-0.81667733 -0.23714767  0.59574044  0.45004386 -0.63921046]
 [-0.19803882  0.56011432  0.00307542  0.42497054 -0.13932276]] [[ 0.88804054 -0.95137119  0.25186515  0.14859891 -0.47235966 -0.25517511
  -0.0501914  -0.60096025  0.54795289  0.68909526]
 [ 0.59614164 -0.24400139  0.38771194 -0.8711015  -0.74931383 -0.40806228
  -0.95175701 -0.49542952 -0.3072648   0.82513708]
 [-0.3088443  -0.59847355  0.11045893  0.58929884 -0.8345046  -0.0740291
   0.76423985 -0.20647335 -0.66622543 -0.82845211]
 [ 0.72971928 -0.5075531   0.68112642  0.6185227  -0.46144533  0.33415046
   0.67870098 -0.86489701  0.10732532  0.84688395]
 [ 0.73057103  0.11658239  0.03234148  0.79900026 -0.06810546 -0.14883804
  -0.93047237 -0.55029798 -0.66590023 -0.8907938 ]]
200 0.00351166 [[-0.81667733 -0.38213074  0.5887146   0.92144883 -0.63921046]
 [-0.19803882  0.31949574 -0.03012698  0.91326529 -0.13932276]] [[ 0.88804054 -0.9513