In [9]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('train3.txt', unpack=True, dtype='float32')

x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.zeros([3, 3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W))

learning_rate = 0.05

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), reduction_indices=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)


init = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init)

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print (step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W))


FileNotFoundError: [Errno 2] No such file or directory: 'train3.txt'

In [10]:
import tensorflow as tf
import numpy as np


xy = np.loadtxt('data/train_xor.txt', unpack=True)
x_data = np.transpose(xy[0:-1])
y_data = np.reshape(xy[-1], (4, 1))

print (x_data)
print (y_data)

X = tf.placeholder(tf.float32, name='x-input')
Y = tf.placeholder(tf.float32, name='y-input')

w1 = tf.Variable(tf.random_uniform([2, 2], -1.0, 1.0), name='weight1')
w2 = tf.Variable(tf.random_uniform([2, 1], -1.0, 1.0), name='weight8')

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

L2 = tf.nn.relu(tf.matmul(X, w1) + b1)
hypothesis = tf.sigmoid(tf.matmul(L2, w2) + b2)

with tf.name_scope('cost') as scope:
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1 - hypothesis))
    cost_summ = tf.scalar_summary("cost", cost)

with tf.name_scope('train') as scope:
    a = tf.Variable(0.1)
    optimizer = tf.train.GradientDescentOptimizer(a)
    train = optimizer.minimize(cost)

w1_hist = tf.histogram_summary("weights1", w1)
w2_hist = tf.histogram_summary("weights2", w2)

b1_hist = tf.histogram_summary("biases1", b1)
b2_hist = tf.histogram_summary("biases2", b2)

y_hist = tf.histogram_summary("y", Y)

init = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init)

    merged = tf.merge_all_summaries()
    writer = tf.train.SummaryWriter("./logs/xor_logs", sess.graph)

    for step in range(2000):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            summary = sess.run(merged, feed_dict={X: x_data, Y: y_data})
            writer.add_summary(summary, step)
            print (step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(w1), sess.run(w2))

    correct_prediction = tf.equal(tf.floor(hypothesis+0.5), Y)

    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    print (sess.run([hypothesis, tf.floor(hypothesis+0.5), correct_prediction], feed_dict={X: x_data, Y: y_data}))
    print ("accuracy", accuracy.eval({X: x_data, Y: y_data}))


[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]
[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]]
0 0.705802 [[-0.8325181   0.75114942]
 [ 0.40126315  0.57999659]] [[ 0.23922026]
 [ 0.53223711]]
200 0.531792 [[-1.27680087  0.72002387]
 [ 1.25830734  0.3591097 ]] [[ 1.54813457]
 [ 0.17480597]]
400 0.436876 [[-1.71117902  0.99242365]
 [ 1.69894755 -0.21029091]] [[ 2.22755718]
 [ 0.64105201]]
600 0.132907 [[-1.94334173  1.64411581]
 [ 1.93805099 -1.65255189]] [[ 2.58150744]
 [ 2.19137907]]
800 0.0604655 [[-2.13223147  2.04015732]
 [ 2.13160491 -2.04180479]] [[ 2.86588264]
 [ 2.77261066]]
1000 0.0374997 [[-2.27307892  2.22817969]
 [ 2.27272964 -2.22688413]] [[ 3.07433414]
 [ 3.04574347]]
1200 0.0267241 [[-2.37869263  2.34492421]
 [ 2.37292337 -2.34741664]] [[ 3.22589827]
 [ 3.21872926]]
1400 0.0204771 [[-2.45543766  2.43098569]
 [ 2.4537065  -2.43323827]] [[ 3.34159803]
 [ 3.34371161]]
1600 0.016525 [[-2.51867247  2.49858522]
 [ 2.51638651 -2.49907374]] [[ 3.43389606]
 [ 3.44059944]]
1800 0.0137858 [[-2.57027173 

In [1]:
import tensorflow as tf
import numpy as np


xy = np.loadtxt('data/train_xor.txt', unpack=True)
x_data = np.transpose(xy[0:-1])
y_data = np.reshape(xy[-1], (4, 1))

print (x_data)
print (y_data)

X = tf.placeholder(tf.float32, name='x-input')
Y = tf.placeholder(tf.float32, name='y-input')

w1 = tf.Variable(tf.random_uniform([2, 2], -1.0, 1.0), name='weight1')
w2 = tf.Variable(tf.random_uniform([2, 1], -1.0, 1.0), name='weight8')

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

L2 = tf.nn.relu(tf.matmul(X, w1) + b1)
hypothesis = tf.sigmoid(tf.matmul(L2, w2) + b2)

with tf.name_scope('cost') as scope:
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1 - hypothesis))
    cost_summ = tf.scalar_summary("cost", cost)

with tf.name_scope('train') as scope:
    a = tf.Variable(0.1)
    optimizer = tf.train.GradientDescentOptimizer(a)
    train = optimizer.minimize(cost)

w1_hist = tf.histogram_summary("weights1", w1)
w2_hist = tf.histogram_summary("weights2", w2)

b1_hist = tf.histogram_summary("biases1", b1)
b2_hist = tf.histogram_summary("biases2", b2)

y_hist = tf.histogram_summary("y", Y)

init = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init)

    merged = tf.merge_all_summaries()
    writer = tf.train.SummaryWriter("./logs/xor_logs", sess.graph)

    for step in range(2000):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            summary = sess.run(merged, feed_dict={X: x_data, Y: y_data})
            writer.add_summary(summary, step)
            print (step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(w1), sess.run(w2))

    correct_prediction = tf.equal(tf.floor(hypothesis+0.5), Y)

    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    print (sess.run([hypothesis, tf.floor(hypothesis+0.5), correct_prediction], feed_dict={X: x_data, Y: y_data}))
    print ("accuracy", accuracy.eval({X: x_data, Y: y_data}))


[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]
[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]]
0 0.755881 [[ 0.42748186  0.25549844]
 [ 0.86219686  0.68550992]] [[ 0.98478162]
 [-0.09681578]]
200 0.693516 [[ 0.25995129  0.29966202]
 [ 0.58419758  0.76989412]] [[ 0.67493623]
 [-0.39727598]]
400 0.590821 [[ 0.27034035  0.78594625]
 [ 0.57572269  0.78884715]] [[ 0.67276913]
 [-1.14423978]]
600 0.346938 [[ 0.87658292  1.54825878]
 [ 0.98837829  1.54729152]] [[ 1.33676863]
 [-2.55721521]]
800 0.164984 [[ 1.43758488  2.12040329]
 [ 1.45260239  2.11304522]] [[ 2.0508728 ]
 [-3.57666063]]
1000 0.0897341 [[ 1.74399495  2.46703339]
 [ 1.74669302  2.46885252]] [[ 2.47243738]
 [-4.19107533]]
1200 0.0570183 [[ 1.93135393  2.68882251]
 [ 1.93269324  2.69036984]] [[ 2.73518443]
 [-4.58244705]]
1400 0.0401754 [[ 2.06069136  2.84424448]
 [ 2.06149125  2.84502649]] [[ 2.91707778]
 [-4.85631084]]
1600 0.0305037 [[ 2.15701509  2.96223378]
 [ 2.15757465  2.96062088]] [[ 3.05276132]
 [-5.06221199]]
1800 0.0243565 [[ 2.2326827  